apiVersion: apps/v1
kind: Deployment         # We are testing the Job resource type
metadata:
  name: zookeeper-deployment  # A name must be given to the Job type in the metadata section
spec:                     # This is the specification where we can even put the number of replicas
  replicas: 1
  selector:
      matchLabels:
        app: zookeeper        # some label to give to this pod (see the matching label above)
  minReadySeconds: 30

  template:                 # actual specification
      metadata:
        labels:
          app: zookeeper
      spec:
        containers:
        - name: zookeeper       # this is going to be used for DNS name
        # Change the IP address to where you are running this
          image: jreiser123/zookeeper  # this is the image in registry accessible
          imagePullPolicy: Always  # This forces the node to pull the image
          command: ["kafka_2.12-3.3.1/bin/zookeeper-server-start.sh"]
          args: ["kafka_2.12-3.3.1/config/zookeeper.properties"]

          ports:
          - containerPort: 2181
          - containerPort: 5984
          - containerPort: 9092
